version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  pgdata:
